version: "3.9"
services:
    web:
        build: riskanalysis/
        container_name: riskanalysis-api
        ports:
            - "8000:8000"
    neo4j:
        image: "neo4j:latest"
        container_name: riskanalysis-neo4j
        ports:
            - "7474:7474"   #HTTP
            - "7473:7473"   #HTTPS
            - "7687:7687"   #Bolt
        environment:
            - NEO4J_AUTH=neo4j/test
            - NEO4JLABS_PLUGINS=["graph-data-science"]
    mongo:
        image: mongo
        container_name: riskanalysis-mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: tilt
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: SuperSecret
    mongo-express:
        image: mongo-express
        container_name: riskanalysis-mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: SuperSecret
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: SuperSecret